# Generated by Django 5.1 on 2024-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscleGroup', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=50)),
                ('equipment_needed', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
