# Generated by Django 5.1 on 2024-09-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_subscribers_remove_exercises_equipment_needed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipedWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.exercises')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.item')),
            ],
        ),
    ]
